# Generated by Django 5.0.4 on 2024-05-13 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinefy_app", "0004_alter_watched_owner_alter_watchlist_owner"),
        ("users", "0002_alter_profile_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watched",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.profile"
            ),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.profile"
            ),
        ),
    ]
