# Generated by Django 5.0.4 on 2024-06-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinefy_app", "0005_alter_watched_owner_alter_watchlist_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="watchlink",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
